apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: todoproject-namespace
  name: dailytask
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: dailytask
            image: TODO/DAILYTASK
          restartPolicy: Never
