apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: todoproject-namespace
  name: project-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Mi
