apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/back.deployment.yaml
  - manifests/back.service.yaml
  - manifests/dailytask.cronjob.yaml
  - manifests/deployment.yaml
  - manifests/ingress.yaml
  - manifests/pg.service.yaml
  - manifests/pg.statefulset.yaml
  - manifests/service.yaml
