apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: todoproject-namespace
  name: todoproject-back-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoproject-back
  template:
    metadata:
      labels:
        app: todoproject-back
    spec:
      volumes:
        - name: project-volume
          persistentVolumeClaim:
            claimName: project-pv-claim
      containers:
        - name: todoproject-back
          image: TODO/BACK
          resources:
            limits:
              cpu: 200m
              memory: 64Mi
          volumeMounts:
          - name: project-volume
            mountPath: /app/files
          envFrom:
            - secretRef:
                name: postgres-pass
