apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: logging-namespace
  name: loggingvol-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16Mi
