apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- back.rollout.yaml
- back.service.yaml
- dailytask.cronjob.yaml
- rollout.yaml
- ingress.yaml
- pg.service.yaml
- pg.statefulset.yaml
- service.yaml
- persistentvolumeclaim.yaml
- analysistemplate.yaml
- broadcaster.service.yaml
- broadcaster.rollout.yaml
- configmap.yaml
- namespace.yaml
images:
- name: IMAGE_PLACEHOLDER
  newName: vhmk/broadcaster
  newTag: a79b6e30bed8a03be3e84f6e034a9751d91a5d69
- name: TODO/BACK
  newName: vhmk/back
  newTag: 35dc0bb005b2c6c12bdb786f5852a474c5bc3649
- name: TODO/BROADCASTER
  newName: vhmk/broadcaster
  newTag: 35dc0bb005b2c6c12bdb786f5852a474c5bc3649
- name: TODO/DAILYTASK
  newName: vhmk/dailytask
  newTag: 35dc0bb005b2c6c12bdb786f5852a474c5bc3649
- name: TODO/FRONT
  newName: vhmk/front
  newTag: 35dc0bb005b2c6c12bdb786f5852a474c5bc3649
