apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  namespace: todoproject-namespace
  name: cpu-analysis
spec:
  metrics:
  - name: cpu-analysis
    initialDelay: 10m
    successCondition: result < 2.5 && result > 0.2
    provider:
      prometheus:
        address: http://kube-prometheus-stack-1657-prometheus.prometheus.svc.cluster.local:9090
        query: |
          scalar(
            sum(
              rate(container_cpu_usage_seconds_total{namespace="todoproject-namespace"}[10m])
            ) * 100
          )
