apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  namespace: todoproject-namespace
  name: todoproject-front-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoproject-front
  strategy:
    # Use default rolling update since there's only one replica
    canary:
      maxSurge: 1
      maxUnavailable: 1
      steps:
      - analysis:
          templates:
          - templateName: cpu-analysis
  template:
    metadata:
      labels:
        app: todoproject-front
    spec:
      containers:
        - name: todoproject-front
          image: TODO/FRONT
          resources:
            limits:
              cpu: 100m
              memory: 64Mi
          readinessProbe:
            initialDelaySeconds: 15
            periodSeconds: 10
            httpGet:
               path: /healthz
               port: 8000
          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 10
            httpGet:
               path: /healthz
               port: 8000
