# Other assignment versions for gh actions are in previous commits:
# part 3 e03: d1a93c3b937bad5f8b4bafbd4125a965f45c6236
# part 3 e04: 024805fcf3e1a80727d4ade36266a2294356ffd7
name: Release application with gitops

on:
  push:
    branches:
      - main
    paths-ignore:
      - "part*/*/manifests/kustomization.yaml"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Frontend
      uses: docker/build-push-action@v2
      with:
        file: part4/e08/front.Dockerfile
        context: part4/e08
        push: true
        tags: vhmk/front:${{ github.sha }}

    - name: Build and Push Backend
      uses: docker/build-push-action@v2
      with:
        file: part4/e08/back.Dockerfile
        context: part4/e08
        push: true
        tags: vhmk/back:${{ github.sha }}

    - name: Build and Push Daily task
      uses: docker/build-push-action@v2
      with:
        file: part4/e08/dailytask.Dockerfile
        context: part4/e08
        push: true
        tags: vhmk/dailytask:${{ github.sha }}

    - name: Build and Push Broadcaster
      uses: docker/build-push-action@v2
      with:
        file: part4/e08/broadcaster.Dockerfile
        context: part4/e08
        push: true
        tags: vhmk/broadcaster:${{ github.sha }}

  deploy:
    name: Deploy Cluster
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v2

    - name: Set up Kustomize
      uses: imranismail/setup-kustomize@v1

    - name: Update yamls
      working-directory: part4/e08/manifests
      run: |-
        kustomize edit set image TODO/FRONT=vhmk/front:${{ github.sha }}
        kustomize edit set image TODO/BACK=vhmk/back:${{ github.sha }}
        kustomize edit set image TODO/DAILYTASK=vhmk/dailytask:${{ github.sha }}
        kustomize edit set image TODO/BROADCASTER=vhmk/broadcaster:${{ github.sha }}

    - uses: EndBug/add-and-commit@v7
      with:
        add: "part4/e08/manifests/kustomization.yaml"
        message: New version release for gitops-app ${{ github.sha }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
