name: Release application

on:
  push:

defaults:
  run:
    shell: bash
    working-directory: part3/e03

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b
  IMAGE: dwk-project
jobs:
  build-publish-deploy:
    name: Build, Publish and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Sops
        uses: mdgreenwald/mozilla-sops-action@v1.2.0
        with:
          version: '3.7.3'
        id: install

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.6.0
        with:
          project_id: ${{ secrets.GKE_PROJECT }}
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          export_default_credentials: true

      - run: gcloud --quiet auth configure-docker
      - run: gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

      - name: Build
        run: |-
          docker build . -f back.Dockerfile --tag "gcr.io/$PROJECT_ID/$IMAGE-back:${GITHUB_REF#refs/heads/}-$GITHUB_SHA"
          docker build . -f front.Dockerfile --tag "gcr.io/$PROJECT_ID/$IMAGE-front:${GITHUB_REF#refs/heads/}-$GITHUB_SHA"
          docker build . -f dailytask.Dockerfile --tag "gcr.io/$PROJECT_ID/$IMAGE-dailytask:${GITHUB_REF#refs/heads/}-$GITHUB_SHA"

      - name: Publish
        run: |-
          docker push "gcr.io/$PROJECT_ID/$IMAGE-back:${GITHUB_REF#refs/heads/}-$GITHUB_SHA"
          docker push "gcr.io/$PROJECT_ID/$IMAGE-front:${GITHUB_REF#refs/heads/}-$GITHUB_SHA"
          docker push "gcr.io/$PROJECT_ID/$IMAGE-dailytask:${GITHUB_REF#refs/heads/}-$GITHUB_SHA"

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v1

      - name: Deploy
        run: |-
          kubectl create namespace todoproject-namespace || true
          kustomize edit set image TODO/BACK=gcr.io/$PROJECT_ID/$IMAGE-back:${GITHUB_REF#refs/heads/}-$GITHUB_SHA
          kustomize edit set image TODO/FRONT=gcr.io/$PROJECT_ID/$IMAGE-front:${GITHUB_REF#refs/heads/}-$GITHUB_SHA
          kustomize edit set image TODO/DAILYTASK=gcr.io/$PROJECT_ID/$IMAGE-dailytask:${GITHUB_REF#refs/heads/}-$GITHUB_SHA
          kustomize build . | cat - <(SOPS_AGE_KEY=$SOPS_AGE_KEY sops --decrypt pg.secret.enc.yaml) | kubectl apply -f -
          kubectl rollout status deployment $IMAGE
          kubectl get services -o wide
